
import { Game, GameType } from './types';

export const ALL_GAMES: Game[] = [
  // Single Player Games
  {
    id: 'ping-pong',
    title: 'Ping Pong',
    tagline: 'Retro paddle-and-ball duel.',
    mode: 'Solo',
    type: GameType.SOLO,
    description: 'A classic retro paddle-and-ball duel with ever-increasing speed. Test your reflexes and see how long you can last!',
    coverArt: 'https://picsum.photos/seed/pingpong/600/800',
  },
  {
    id: 'pixel-runner',
    title: 'Pixel Runner',
    tagline: 'Endless side-scrolling action.',
    mode: 'Solo',
    type: GameType.SOLO,
    description: 'An endless side-scroller where you must dodge obstacles and collect glowing orbs. Unlock new skins and environments as you achieve higher scores.',
    coverArt: 'https://picsum.photos/seed/pixelrunner/600/800',
  },
  {
    id: 'mind-merge',
    title: 'Mind Merge',
    tagline: 'Connect logic nodes at speed.',
    mode: 'Solo',
    type: GameType.SOLO,
    description: 'A fast-paced puzzle game. Connect logic nodes or matching symbols before the time runs out. How fast can your brain work?',
    coverArt: 'https://picsum.photos/seed/mindmerge/600/800',
  },
  {
    id: '7k-chess-blitz',
    title: '7K Chess Blitz',
    tagline: 'One-minute chess with power-ups.',
    mode: 'Solo',
    type: GameType.SOLO,
    description: 'Experience chess like never before! A one-minute blitz with game-changing power-ups like Undo, Double Move, or Freeze Opponent.',
    coverArt: 'https://picsum.photos/seed/chessblitz/600/800',
  },
  {
    id: 'city-builder-lite',
    title: 'City Builder Lite',
    tagline: 'Build a small island town.',
    mode: 'Solo',
    type: GameType.SOLO,
    description: 'Become the mayor of your own small island town. Balance happiness, power, and the economy to create a thriving community.',
    coverArt: 'https://picsum.photos/seed/citybuilder/600/800',
  },
  {
    id: 'space-miner-tycoon',
    title: 'Space Miner Tycoon',
    tagline: 'Mine asteroids, upgrade ships.',
    mode: 'Solo',
    type: GameType.SOLO,
    description: 'Tap or drag to mine valuable asteroids, upgrade your fleet of ships, and sell rare materials to become a galactic tycoon.',
    coverArt: 'https://picsum.photos/seed/spaceminer/600/800',
  },
  {
    id: 'memory-vault',
    title: 'Memory Vault',
    tagline: 'Recall increasingly hard sequences.',
    mode: 'Solo',
    type: GameType.SOLO,
    description: 'Test your memory by recalling sequences of symbols, sounds, or words that get progressively faster and more complex.',
    coverArt: 'https://picsum.photos/seed/memoryvault/600/800',
  },
  {
    id: 'shadow-duel',
    title: 'Shadow Duel (AI)',
    tagline: 'Timing-based sword fighting.',
    mode: 'Solo',
    type: GameType.SOLO,
    description: 'Enter the sword-fighting arena against a skilled AI. Master timing-based parries and strikes to claim victory.',
    coverArt: 'https://picsum.photos/seed/shadowduel/600/800',
  },
  // Multiplayer Games
  {
    id: 'tap-titans',
    title: 'Tap Titans',
    tagline: 'Tap to defeat a shared boss.',
    mode: '2-4 Players',
    type: GameType.MULTIPLAYER,
    description: 'Team up to take down a massive boss! Each player taps their zone to attack. Grab random power-ups for crucial boosts.',
    coverArt: 'https://picsum.photos/seed/taptitans/600/800',
  },
  {
    id: 'dodge-circle',
    title: 'Dodge Circle',
    tagline: 'Last one to crash wins.',
    mode: '2-4 Players',
    type: GameType.MULTIPLAYER,
    description: 'Control tiny dots that circle a field of dangerous obstacles. Deftly navigate the chaos. The last player to crash wins!',
    coverArt: 'https://picsum.photos/seed/dodgecircle/600/800',
  },
  {
    id: 'tank-royale',
    title: 'Tank Royale',
    tagline: 'Top-down tank mayhem.',
    mode: '2-4 Players',
    type: GameType.MULTIPLAYER,
    description: 'A frantic top-down tank battle. Bounce bullets off walls, use cover, and outlast your opponents in this chaotic arena.',
    coverArt: 'https://picsum.photos/seed/tankroyale/600/800',
  },
  {
    id: 'tug-of-tap',
    title: 'Tug of Tap',
    tagline: 'The ultimate tapping duel.',
    mode: '2 Players',
    type: GameType.MULTIPLAYER,
    description: 'A simple yet intense two-player showdown. Tap your side as fast as you can to pull the rope to your victory line. Surprise power zones add a twist!',
    coverArt: 'https://picsum.photos/seed/tugoftap/600/800',
  },
  {
    id: 'food-frenzy',
    title: 'Food Frenzy',
    tagline: 'Catch food, steal from others.',
    mode: '3-4 Players',
    type: GameType.MULTIPLAYER,
    description: 'It\'s a chaotic feast! Catch falling food that matches your plate color. Steal from your friends to rack up extra points and secure the win.',
    coverArt: 'https://picsum.photos/seed/foodfrenzy/600/800',
  },
  {
    id: 'maze-escape',
    title: 'Maze Escape',
    tagline: 'Co-op to escape the maze.',
    mode: '2-3 Players Co-op',
    type: GameType.MULTIPLAYER,
    description: 'You\'re trapped! Work together with your friends, using unique character abilities, to navigate and escape a trap-filled maze.',
    coverArt: 'https://picsum.photos/seed/mazeescape/600/800',
  },
  {
    id: 'last-square-standing',
    title: 'Last Square Standing',
    tagline: 'Survive on a vanishing grid.',
    mode: '2-4 Players',
    type: GameType.MULTIPLAYER,
    description: 'The floor is disappearing! Move across a vanishing grid and try to push your opponents off. Be the last one standing to win.',
    coverArt: 'https://picsum.photos/seed/lastsquare/600/800',
  },
];
